apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: 2048-generator
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/DanielYevelkin/argocd-fuckery.git
        revision: HEAD
        directories:
          - path: "applications/*"
  template:
    metadata:
      name: '{{.path.basename}}-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/DanielYevelkin/argocd-fuckery.git
        path: '{{ .path.path }}'
        targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true